___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
np.__version__

'1.19.1'

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/daryna/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/daryna/miniconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/daryna/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/daryna/miniconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/daryna/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/daryna/miniconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/daryna/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/daryna/miniconda3/include']


Створити вектор з 10 елементів, заповнений одиницями:

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [6]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [8]:
np.full((5, 5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [14]:
a = np.random.randint(0, 20, (20))
index = np.nonzero(a)
index

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),)

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [15]:
np.average(a)

10.0

In [19]:
np.mean(a)

10.0

In [16]:
np.median(a)

10.5

In [17]:
np.std(a)

5.431390245600108

Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [3]:
p = np.random.randint(1, 10, (4,2))
p

array([[1, 1],
       [2, 1],
       [2, 4],
       [4, 6]])

In [4]:
d = np.random.randint(1, 10, (2,2))
d

array([[1, 9],
       [2, 1]])

In [18]:
s = np.matmul(p, d)
s

array([[ 3, 10],
       [ 4, 19],
       [10, 22],
       [16, 42]])

In [19]:
np.dot(p, d)

array([[ 3, 10],
       [ 4, 19],
       [10, 22],
       [16, 42]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [20]:
s= s.flatten()
s

array([ 3, 10,  4, 19, 10, 22, 16, 42])

In [21]:
np.max(s)

42

In [22]:
np.min(s)

3

In [23]:
s[s==np.min(s)]=0
s

array([ 0, 10,  4, 19, 10, 22, 16, 42])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [25]:
np.corrcoef(s)

1.0

Дано матрицю. Знайти ранг матриці:

In [7]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [6]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [9]:
np.linalg.eig(a)

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
        -4.56760167-3.20389947j]),
 array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
         -0.31386258+0.47450898j],
        [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
         -0.07049527-0.4090732j ],
        [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
          0.7099444 -0.j        ]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [14]:
a = np.random.randint(0,10,50)
print(a)
np.bincount(a).argmax()

[8 2 3 4 2 3 4 3 3 1 0 3 8 3 0 2 8 1 9 8 5 6 3 0 7 7 8 3 9 9 8 8 6 0 9 3 2
 2 8 8 4 0 8 5 3 1 8 6 8 7]


8

Виведіть лише парні числа, що діляться на 5:

In [18]:
a = np.random.randint(0,10,50)
print(a)

a[(a % 2 == 0) & (a % 5 == 0)]

[1 6 6 3 5 2 7 1 6 0 2 2 4 4 6 7 1 9 9 1 1 4 9 1 8 9 5 5 2 4 3 2 5 5 8 5 2
 7 4 4 2 3 1 8 5 2 4 9 4 4]


array([0])

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [19]:
array1 = np.array([[2, 5],[1, -10]])
array2 = np.array([1,3])

solution = np.linalg.solve(array1,array2)
solution

array([ 1. , -0.2])